version: '3.3'

services:
  app:
    image: node:18
    container_name: exads_node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3005:3005'
    command: bash -c "yarn install && yarn start"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.2
    container_name: exads_mongo
    ports:
      - 27017:27017
  redis:
    image: redis:7
    container_name: exads_redis
    command: bash -c "redis-server"
    ports:
      - 6379:6379
